### ISSUE TITLE
AttributeError: 'GSNetwork' object has no attribute 'named_children'

### ISSUE THREAD

**Issue by beibeirory** [zjy526223908/TIP-Editor#4]
run "bash run_doll_sunglasses1.sh ", an error occurred.
Can you give me some suggestions? And can you share the version of xformers?
Traceback (most recent call last):
  File "/home/llh/experiments/code/Editor/TIP-Editor/train_3DGS.py", line 98, in <module>
    trainer = Trainer_3DGS('df', opt, model, guidance, device=device, workspace=opt.workspace, fp16=opt.fp16, use_checkpoint=opt.ckpt)
  File "/home/llh/experiments/code/Editor/TIP-Editor/models/trainer_3dgs.py", line 76, in __init__
    model = torch.nn.SyncBatchNorm.convert_sync_batchnorm(model)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 814, in convert_sync_batchnorm
    for name, child in module.named_children():
AttributeError: 'GSNetwork' object has no attribute 'named_children'
Exception ignored in: <function Trainer_3DGS.__del__ at 0x7f683d12caf0>
Traceback (most recent call last):
  File "/home/llh/experiments/code/Editor/TIP-Editor/models/trainer_3dgs.py", line 157, in __del__
    if self.log_ptr:
AttributeError: 'Trainer_3DGS' object has no attribute 'log_ptr'
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
04/29/2024 15:46:38 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'timestep_spacing', 'sample_max_value', 'dynamic_thresholding_ratio', 'prediction_type', 'variance_type', 'clip_sample_range', 'thresholding'} was not found in config. Values will be initialized to default values.
{'scaling_factor', 'force_upcast'} was not found in config. Values will be initialized to default values.
{'resnet_out_scale_factor', 'conv_out_kernel', 'dropout', 'time_embedding_type', 'time_cond_proj_dim', 'encoder_hid_dim', 'transformer_layers_per_block', 'time_embedding_dim', 'time_embedding_act_fn', 'num_class_embeds', 'only_cross_attention', 'encoder_hid_dim_type', 'cross_attention_norm', 'mid_block_type', 'mid_block_only_cross_attention', 'num_attention_heads', 'resnet_skip_time_act', 'addition_embed_type_num_heads', 'upcast_attention', 'class_embed_type', 'timestep_post_act', 'resnet_time_scale_shift', 'addition_time_embed_dim', 'attention_type', 'class_embeddings_concat', 'addition_embed_type', 'reverse_transformer_layers_per_block', 'conv_in_kernel', 'projection_class_embeddings_input_dim'} was not found in config. Values will be initialized to default values.
Loading pipeline components...:   0%|                                                                              | 0/6 [00:00<?, ?it/s]{'scaling_factor', 'force_upcast'} was not found in config. Values will be initialized to default values.
Loaded vae as AutoencoderKL from `vae` subfolder of stabilityai/stable-diffusion-2-1-base.
{'timestep_spacing', 'prediction_type'} was not found in config. Values will be initialized to default values.
Loaded scheduler as PNDMScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-2-1-base.
Loaded feature_extractor as CLIPImageProcessor from `feature_extractor` subfolder of stabilityai/stable-diffusion-2-1-base.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 175.79it/s]
04/29/2024 15:46:43 - INFO - __main__ - ***** Running training *****
04/29/2024 15:46:43 - INFO - __main__ -   Num examples = 200
04/29/2024 15:46:43 - INFO - __main__ -   Num batches each epoch = 200
04/29/2024 15:46:43 - INFO - __main__ -   Num Epochs = 5
04/29/2024 15:46:43 - INFO - __main__ -   Instantaneous batch size per device = 1
04/29/2024 15:46:43 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
04/29/2024 15:46:43 - INFO - __main__ -   Gradient Accumulation steps = 1
04/29/2024 15:46:43 - INFO - __main__ -   Total optimization steps = 1000
Steps:   0%|                                                                                                    | 0/1000 [00:00<?, ?it/s]04/29/2024 15:46:43 - INFO - __main__ - Running validation... 
 Generating 2 images with prompt: a photo of a <ktn> plush toy wearing a sunglasses.
                                                                                                                                        {'scaling_factor', 'force_upcast'} was not found in config. Values will be initialized to default values.           | 0/6 [00:00<?, ?it/s]
Loaded vae as AutoencoderKL from `vae` subfolder of stabilityai/stable-diffusion-2-1-base.
{'timestep_spacing', 'prediction_type'} was not found in config. Values will be initialized to default values.
Loaded scheduler as PNDMScheduler from `scheduler` subfolder of stabilityai/stable-diffusion-2-1-base.
Loaded feature_extractor as CLIPImageProcessor from `feature_extractor` subfolder of stabilityai/stable-diffusion-2-1-base.
Loading pipeline components...: 100%|█████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 215.57it/s]
{'timestep_spacing', 'sample_max_value', 'dynamic_thresholding_ratio', 'prediction_type', 'rescale_betas_zero_snr', 'clip_sample_range', 'thresholding'} was not found in config. Values will be initialized to default values.
/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/pipelines/pipeline_utils.py:745: FutureWarning: `torch_dtype` is deprecated and will be removed in version 0.25.0. 
  deprecate("torch_dtype", "0.25.0", "")
/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py:251: FutureWarning: `_encode_prompt()` is deprecated and it will be removed in a future version. Use `encode_prompt()` instead. Also, be aware that the output format changed from a concatenated tensor to a tuple.
  deprecate("_encode_prompt()", "1.0.0", deprecation_message, standard_warn=False)
Steps:   0%|                                                                                          | 1/1000 [00:16<4:34:56, 16.51s/it]Traceback (most recent call last):
  File "/home/llh/experiments/code/Editor/TIP-Editor/personalization/scene_personalization.py", line 1623, in <module>
    main(args)
  File "/home/llh/experiments/code/Editor/TIP-Editor/personalization/scene_personalization.py", line 1439, in main
    model_pred = unet(
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 1066, in forward
    sample, res_samples = downsample_block(
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/unet_2d_blocks.py", line 1160, in forward
    hidden_states = attn(
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/transformer_2d.py", line 374, in forward
    hidden_states = block(
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/attention.py", line 328, in forward
    ff_output = self.ff(norm_hidden_states, scale=lora_scale)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/attention.py", line 393, in forward
    hidden_states = module(hidden_states, scale)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/llh/experiments/miniconda3/envs/tipeditor/lib/python3.9/site-packages/diffusers/models/activations.py", line 101, in forward
    return hidden_states * self.gelu(gate)
RuntimeError: CUDA out of memory. Tried to allocate 10.00 MiB (GPU 0; 23.67 GiB total capacity; 21.31 GiB already allocated; 40.94 MiB free; 21.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                          | 1/1000 [00:16<4:40:47, 16.86s/it]

**Comment by beibeirory** [comment]
Can you provide the details about GPUs during the training process? @zjy526223908
